// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE
'use strict';

var Js_mapperRt = require("bs-platform/lib/js/js_mapperRt.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var Js_null_undefined = require("bs-platform/lib/js/js_null_undefined.js");
var SemanticUiReact = require("semantic-ui-react");

var jsMapperConstantArray = /* array */[
  /* tuple */[
    -1068897462,
    "grenada"
  ],
  /* tuple */[
    -1058104637,
    "belgium"
  ],
  /* tuple */[
    -1057198893,
    "us minor islands"
  ],
  /* tuple */[
    -1053402039,
    "kiribati"
  ],
  /* tuple */[
    -1044422968,
    "chad"
  ],
  /* tuple */[
    -1043776271,
    "cuba"
  ],
  /* tuple */[
    -1042516348,
    "bolivia"
  ],
  /* tuple */[
    -1039556061,
    "italy"
  ],
  /* tuple */[
    -1039312774,
    "djibouti"
  ],
  /* tuple */[
    -1027060436,
    "sweden"
  ],
  /* tuple */[
    -1022963217,
    "united kingdom"
  ],
  /* tuple */[
    -1011102526,
    "fiji"
  ],
  /* tuple */[
    -999418214,
    "guam"
  ],
  /* tuple */[
    -987822576,
    "wales"
  ],
  /* tuple */[
    -977688163,
    "chile"
  ],
  /* tuple */[
    -977687721,
    "china"
  ],
  /* tuple */[
    -977388266,
    "iran"
  ],
  /* tuple */[
    -977388263,
    "iraq"
  ],
  /* tuple */[
    -964880024,
    "kazakhstan"
  ],
  /* tuple */[
    -957596254,
    "hungary"
  ],
  /* tuple */[
    -951506317,
    "azerbaijan"
  ],
  /* tuple */[
    -950001151,
    "monaco"
  ],
  /* tuple */[
    -947590555,
    "saint vincent"
  ],
  /* tuple */[
    -944961831,
    "laos"
  ],
  /* tuple */[
    -933872943,
    "mali"
  ],
  /* tuple */[
    -924024570,
    "japan"
  ],
  /* tuple */[
    -922383541,
    "niue"
  ],
  /* tuple */[
    -911523698,
    "america"
  ],
  /* tuple */[
    -911099509,
    "oman"
  ],
  /* tuple */[
    -900403976,
    "peru"
  ],
  /* tuple */[
    -899813654,
    "congo"
  ],
  /* tuple */[
    -898192201,
    "bouvet island"
  ],
  /* tuple */[
    -898121627,
    "northern mariana islands"
  ],
  /* tuple */[
    -887842291,
    "us virgin islands"
  ],
  /* tuple */[
    -855550877,
    "togo"
  ],
  /* tuple */[
    -854265839,
    "antigua"
  ],
  /* tuple */[
    -828834904,
    "british virgin islands"
  ],
  /* tuple */[
    -804512446,
    "slovakia"
  ],
  /* tuple */[
    -792880747,
    "qatar"
  ],
  /* tuple */[
    -789091961,
    "gambia"
  ],
  /* tuple */[
    -783133411,
    "pakistan"
  ],
  /* tuple */[
    -779889051,
    "macedonia"
  ],
  /* tuple */[
    -773945724,
    "indonesia"
  ],
  /* tuple */[
    -766413858,
    "georgia"
  ],
  /* tuple */[
    -765509457,
    "guinea"
  ],
  /* tuple */[
    -760004991,
    "slovenia"
  ],
  /* tuple */[
    -747862421,
    "croatia"
  ],
  /* tuple */[
    -729080503,
    "botswana"
  ],
  /* tuple */[
    -722345145,
    "thailand"
  ],
  /* tuple */[
    -722135125,
    "mauritius"
  ],
  /* tuple */[
    -721762895,
    "sao tome"
  ],
  /* tuple */[
    -720838877,
    "switzerland"
  ],
  /* tuple */[
    -714087729,
    "latvia"
  ],
  /* tuple */[
    -705525977,
    "bahamas"
  ],
  /* tuple */[
    -704218920,
    "tajikistan"
  ],
  /* tuple */[
    -696747780,
    "uganda"
  ],
  /* tuple */[
    -687900996,
    "cote divoire"
  ],
  /* tuple */[
    -646435008,
    "sierra leone"
  ],
  /* tuple */[
    -642458078,
    "new zealand"
  ],
  /* tuple */[
    -640701457,
    "rwanda"
  ],
  /* tuple */[
    -637331813,
    "caicos islands"
  ],
  /* tuple */[
    -633260093,
    "western sahara"
  ],
  /* tuple */[
    -622404468,
    "solomon islands"
  ],
  /* tuple */[
    -621724693,
    "nicaragua"
  ],
  /* tuple */[
    -621278036,
    "south africa"
  ],
  /* tuple */[
    -618012032,
    "gb sct"
  ],
  /* tuple */[
    -617811110,
    "gb wls"
  ],
  /* tuple */[
    -606042658,
    "cayman islands"
  ],
  /* tuple */[
    -602620707,
    "armenia"
  ],
  /* tuple */[
    -597476437,
    "guinea bissau"
  ],
  /* tuple */[
    -592181517,
    "anguilla"
  ],
  /* tuple */[
    -588720855,
    "guyana"
  ],
  /* tuple */[
    -577111240,
    "south korea"
  ],
  /* tuple */[
    -570269089,
    "european union"
  ],
  /* tuple */[
    -564919854,
    "bhutan"
  ],
  /* tuple */[
    -554270628,
    "kenya"
  ],
  /* tuple */[
    -529684496,
    "north korea"
  ],
  /* tuple */[
    -517598307,
    "bahrain"
  ],
  /* tuple */[
    -514188122,
    "jan mayen"
  ],
  /* tuple */[
    -484744694,
    "angola"
  ],
  /* tuple */[
    -482760220,
    "falkland islands"
  ],
  /* tuple */[
    -476616148,
    "faroe islands"
  ],
  /* tuple */[
    -456450688,
    "bosnia"
  ],
  /* tuple */[
    -421118987,
    "palestine"
  ],
  /* tuple */[
    -399377774,
    "cameroon"
  ],
  /* tuple */[
    -392688584,
    "cape verde"
  ],
  /* tuple */[
    -380981227,
    "romania"
  ],
  /* tuple */[
    -380657802,
    "barbados"
  ],
  /* tuple */[
    -380046428,
    "singapore"
  ],
  /* tuple */[
    -373341036,
    "zambia"
  ],
  /* tuple */[
    -355065672,
    "panama"
  ],
  /* tuple */[
    -351202479,
    "nigeria"
  ],
  /* tuple */[
    -343241121,
    "netherlands antilles"
  ],
  /* tuple */[
    -337001573,
    "egypt"
  ],
  /* tuple */[
    -303738810,
    "lesotho"
  ],
  /* tuple */[
    -299359974,
    "serbia"
  ],
  /* tuple */[
    -292434998,
    "yemen"
  ],
  /* tuple */[
    -282086119,
    "saint kitts and nevis"
  ],
  /* tuple */[
    -263326618,
    "burkina faso"
  ],
  /* tuple */[
    -228119709,
    "united arab emirates"
  ],
  /* tuple */[
    -227222789,
    "mayotte"
  ],
  /* tuple */[
    -187153541,
    "malaysia"
  ],
  /* tuple */[
    -185019315,
    "libya"
  ],
  /* tuple */[
    -184298209,
    "kuwait"
  ],
  /* tuple */[
    -181160755,
    "congo brazzaville"
  ],
  /* tuple */[
    -176061488,
    "mongolia"
  ],
  /* tuple */[
    -162377560,
    "gibraltar"
  ],
  /* tuple */[
    -147839491,
    "estonia"
  ],
  /* tuple */[
    -142246159,
    "samoa"
  ],
  /* tuple */[
    -115354774,
    "poland"
  ],
  /* tuple */[
    -91906648,
    "czech republic"
  ],
  /* tuple */[
    -89167226,
    "paraguay"
  ],
  /* tuple */[
    -80447856,
    "netherlands"
  ],
  /* tuple */[
    -80381167,
    "central african republic"
  ],
  /* tuple */[
    -73931685,
    "turkmenistan"
  ],
  /* tuple */[
    -63926047,
    "mauritania"
  ],
  /* tuple */[
    -30286144,
    "israel"
  ],
  /* tuple */[
    -21768663,
    "lithuania"
  ],
  /* tuple */[
    21731,
    "ad"
  ],
  /* tuple */[
    21732,
    "ae"
  ],
  /* tuple */[
    21733,
    "af"
  ],
  /* tuple */[
    21734,
    "ag"
  ],
  /* tuple */[
    21736,
    "ai"
  ],
  /* tuple */[
    21739,
    "al"
  ],
  /* tuple */[
    21740,
    "am"
  ],
  /* tuple */[
    21741,
    "an"
  ],
  /* tuple */[
    21742,
    "ao"
  ],
  /* tuple */[
    21745,
    "ar"
  ],
  /* tuple */[
    21747,
    "at"
  ],
  /* tuple */[
    21748,
    "au"
  ],
  /* tuple */[
    21750,
    "aw"
  ],
  /* tuple */[
    21751,
    "ax"
  ],
  /* tuple */[
    21753,
    "az"
  ],
  /* tuple */[
    21951,
    "ba"
  ],
  /* tuple */[
    21952,
    "bb"
  ],
  /* tuple */[
    21954,
    "bd"
  ],
  /* tuple */[
    21955,
    "be"
  ],
  /* tuple */[
    21956,
    "bf"
  ],
  /* tuple */[
    21957,
    "bg"
  ],
  /* tuple */[
    21958,
    "bh"
  ],
  /* tuple */[
    21959,
    "bi"
  ],
  /* tuple */[
    21960,
    "bj"
  ],
  /* tuple */[
    21963,
    "bm"
  ],
  /* tuple */[
    21964,
    "bn"
  ],
  /* tuple */[
    21965,
    "bo"
  ],
  /* tuple */[
    21968,
    "br"
  ],
  /* tuple */[
    21969,
    "bs"
  ],
  /* tuple */[
    21970,
    "bt"
  ],
  /* tuple */[
    21972,
    "bv"
  ],
  /* tuple */[
    21973,
    "bw"
  ],
  /* tuple */[
    21975,
    "by"
  ],
  /* tuple */[
    21976,
    "bz"
  ],
  /* tuple */[
    22174,
    "ca"
  ],
  /* tuple */[
    22176,
    "cc"
  ],
  /* tuple */[
    22177,
    "cd"
  ],
  /* tuple */[
    22179,
    "cf"
  ],
  /* tuple */[
    22180,
    "cg"
  ],
  /* tuple */[
    22181,
    "ch"
  ],
  /* tuple */[
    22182,
    "ci"
  ],
  /* tuple */[
    22184,
    "ck"
  ],
  /* tuple */[
    22185,
    "cl"
  ],
  /* tuple */[
    22186,
    "cm"
  ],
  /* tuple */[
    22187,
    "cn"
  ],
  /* tuple */[
    22188,
    "co"
  ],
  /* tuple */[
    22191,
    "cr"
  ],
  /* tuple */[
    22192,
    "cs"
  ],
  /* tuple */[
    22194,
    "cu"
  ],
  /* tuple */[
    22195,
    "cv"
  ],
  /* tuple */[
    22197,
    "cx"
  ],
  /* tuple */[
    22198,
    "cy"
  ],
  /* tuple */[
    22199,
    "cz"
  ],
  /* tuple */[
    22401,
    "de"
  ],
  /* tuple */[
    22406,
    "dj"
  ],
  /* tuple */[
    22407,
    "dk"
  ],
  /* tuple */[
    22409,
    "dm"
  ],
  /* tuple */[
    22422,
    "dz"
  ],
  /* tuple */[
    22622,
    "ec"
  ],
  /* tuple */[
    22624,
    "ee"
  ],
  /* tuple */[
    22626,
    "eg"
  ],
  /* tuple */[
    22627,
    "eh"
  ],
  /* tuple */[
    22637,
    "er"
  ],
  /* tuple */[
    22638,
    "es"
  ],
  /* tuple */[
    22639,
    "et"
  ],
  /* tuple */[
    22640,
    "eu"
  ],
  /* tuple */[
    22851,
    "fi"
  ],
  /* tuple */[
    22852,
    "fj"
  ],
  /* tuple */[
    22853,
    "fk"
  ],
  /* tuple */[
    22855,
    "fm"
  ],
  /* tuple */[
    22857,
    "fo"
  ],
  /* tuple */[
    22860,
    "fr"
  ],
  /* tuple */[
    23066,
    "ga"
  ],
  /* tuple */[
    23067,
    "gb"
  ],
  /* tuple */[
    23069,
    "gd"
  ],
  /* tuple */[
    23070,
    "ge"
  ],
  /* tuple */[
    23071,
    "gf"
  ],
  /* tuple */[
    23073,
    "gh"
  ],
  /* tuple */[
    23074,
    "gi"
  ],
  /* tuple */[
    23077,
    "gl"
  ],
  /* tuple */[
    23078,
    "gm"
  ],
  /* tuple */[
    23079,
    "gn"
  ],
  /* tuple */[
    23081,
    "gp"
  ],
  /* tuple */[
    23082,
    "gq"
  ],
  /* tuple */[
    23083,
    "gr"
  ],
  /* tuple */[
    23084,
    "gs"
  ],
  /* tuple */[
    23085,
    "gt"
  ],
  /* tuple */[
    23086,
    "gu"
  ],
  /* tuple */[
    23088,
    "gw"
  ],
  /* tuple */[
    23090,
    "gy"
  ],
  /* tuple */[
    23299,
    "hk"
  ],
  /* tuple */[
    23301,
    "hm"
  ],
  /* tuple */[
    23302,
    "hn"
  ],
  /* tuple */[
    23306,
    "hr"
  ],
  /* tuple */[
    23308,
    "ht"
  ],
  /* tuple */[
    23309,
    "hu"
  ],
  /* tuple */[
    23515,
    "id"
  ],
  /* tuple */[
    23516,
    "ie"
  ],
  /* tuple */[
    23523,
    "il"
  ],
  /* tuple */[
    23526,
    "io"
  ],
  /* tuple */[
    23528,
    "iq"
  ],
  /* tuple */[
    23529,
    "ir"
  ],
  /* tuple */[
    23530,
    "is"
  ],
  /* tuple */[
    23531,
    "it"
  ],
  /* tuple */[
    23747,
    "jm"
  ],
  /* tuple */[
    23749,
    "jo"
  ],
  /* tuple */[
    23750,
    "jp"
  ],
  /* tuple */[
    23962,
    "ke"
  ],
  /* tuple */[
    23964,
    "kg"
  ],
  /* tuple */[
    23965,
    "kh"
  ],
  /* tuple */[
    23966,
    "ki"
  ],
  /* tuple */[
    23970,
    "km"
  ],
  /* tuple */[
    23971,
    "kn"
  ],
  /* tuple */[
    23973,
    "kp"
  ],
  /* tuple */[
    23975,
    "kr"
  ],
  /* tuple */[
    23980,
    "kw"
  ],
  /* tuple */[
    23982,
    "ky"
  ],
  /* tuple */[
    23983,
    "kz"
  ],
  /* tuple */[
    24181,
    "la"
  ],
  /* tuple */[
    24182,
    "lb"
  ],
  /* tuple */[
    24183,
    "lc"
  ],
  /* tuple */[
    24189,
    "li"
  ],
  /* tuple */[
    24191,
    "lk"
  ],
  /* tuple */[
    24198,
    "lr"
  ],
  /* tuple */[
    24199,
    "ls"
  ],
  /* tuple */[
    24200,
    "lt"
  ],
  /* tuple */[
    24201,
    "lu"
  ],
  /* tuple */[
    24202,
    "lv"
  ],
  /* tuple */[
    24205,
    "ly"
  ],
  /* tuple */[
    24404,
    "ma"
  ],
  /* tuple */[
    24406,
    "mc"
  ],
  /* tuple */[
    24407,
    "md"
  ],
  /* tuple */[
    24408,
    "me"
  ],
  /* tuple */[
    24410,
    "mg"
  ],
  /* tuple */[
    24411,
    "mh"
  ],
  /* tuple */[
    24414,
    "mk"
  ],
  /* tuple */[
    24415,
    "ml"
  ],
  /* tuple */[
    24416,
    "mm"
  ],
  /* tuple */[
    24417,
    "mn"
  ],
  /* tuple */[
    24418,
    "mo"
  ],
  /* tuple */[
    24419,
    "mp"
  ],
  /* tuple */[
    24420,
    "mq"
  ],
  /* tuple */[
    24421,
    "mr"
  ],
  /* tuple */[
    24422,
    "ms"
  ],
  /* tuple */[
    24423,
    "mt"
  ],
  /* tuple */[
    24424,
    "mu"
  ],
  /* tuple */[
    24425,
    "mv"
  ],
  /* tuple */[
    24426,
    "mw"
  ],
  /* tuple */[
    24427,
    "mx"
  ],
  /* tuple */[
    24428,
    "my"
  ],
  /* tuple */[
    24429,
    "mz"
  ],
  /* tuple */[
    24627,
    "na"
  ],
  /* tuple */[
    24629,
    "nc"
  ],
  /* tuple */[
    24631,
    "ne"
  ],
  /* tuple */[
    24632,
    "nf"
  ],
  /* tuple */[
    24633,
    "ng"
  ],
  /* tuple */[
    24635,
    "ni"
  ],
  /* tuple */[
    24638,
    "nl"
  ],
  /* tuple */[
    24641,
    "no"
  ],
  /* tuple */[
    24642,
    "np"
  ],
  /* tuple */[
    24644,
    "nr"
  ],
  /* tuple */[
    24647,
    "nu"
  ],
  /* tuple */[
    24652,
    "nz"
  ],
  /* tuple */[
    24862,
    "om"
  ],
  /* tuple */[
    25073,
    "pa"
  ],
  /* tuple */[
    25077,
    "pe"
  ],
  /* tuple */[
    25078,
    "pf"
  ],
  /* tuple */[
    25079,
    "pg"
  ],
  /* tuple */[
    25080,
    "ph"
  ],
  /* tuple */[
    25083,
    "pk"
  ],
  /* tuple */[
    25084,
    "pl"
  ],
  /* tuple */[
    25085,
    "pm"
  ],
  /* tuple */[
    25086,
    "pn"
  ],
  /* tuple */[
    25090,
    "pr"
  ],
  /* tuple */[
    25091,
    "ps"
  ],
  /* tuple */[
    25092,
    "pt"
  ],
  /* tuple */[
    25095,
    "pw"
  ],
  /* tuple */[
    25097,
    "py"
  ],
  /* tuple */[
    25296,
    "qa"
  ],
  /* tuple */[
    25523,
    "re"
  ],
  /* tuple */[
    25533,
    "ro"
  ],
  /* tuple */[
    25537,
    "rs"
  ],
  /* tuple */[
    25539,
    "ru"
  ],
  /* tuple */[
    25541,
    "rw"
  ],
  /* tuple */[
    25742,
    "sa"
  ],
  /* tuple */[
    25743,
    "sb"
  ],
  /* tuple */[
    25744,
    "sc"
  ],
  /* tuple */[
    25745,
    "sd"
  ],
  /* tuple */[
    25746,
    "se"
  ],
  /* tuple */[
    25748,
    "sg"
  ],
  /* tuple */[
    25749,
    "sh"
  ],
  /* tuple */[
    25750,
    "si"
  ],
  /* tuple */[
    25751,
    "sj"
  ],
  /* tuple */[
    25752,
    "sk"
  ],
  /* tuple */[
    25753,
    "sl"
  ],
  /* tuple */[
    25754,
    "sm"
  ],
  /* tuple */[
    25755,
    "sn"
  ],
  /* tuple */[
    25756,
    "so"
  ],
  /* tuple */[
    25759,
    "sr"
  ],
  /* tuple */[
    25761,
    "st"
  ],
  /* tuple */[
    25763,
    "sv"
  ],
  /* tuple */[
    25766,
    "sy"
  ],
  /* tuple */[
    25767,
    "sz"
  ],
  /* tuple */[
    25967,
    "tc"
  ],
  /* tuple */[
    25968,
    "td"
  ],
  /* tuple */[
    25970,
    "tf"
  ],
  /* tuple */[
    25971,
    "tg"
  ],
  /* tuple */[
    25972,
    "th"
  ],
  /* tuple */[
    25974,
    "tj"
  ],
  /* tuple */[
    25975,
    "tk"
  ],
  /* tuple */[
    25976,
    "tl"
  ],
  /* tuple */[
    25977,
    "tm"
  ],
  /* tuple */[
    25978,
    "tn"
  ],
  /* tuple */[
    25982,
    "tr"
  ],
  /* tuple */[
    25984,
    "tt"
  ],
  /* tuple */[
    25986,
    "tv"
  ],
  /* tuple */[
    25987,
    "tw"
  ],
  /* tuple */[
    25990,
    "tz"
  ],
  /* tuple */[
    26188,
    "ua"
  ],
  /* tuple */[
    26194,
    "ug"
  ],
  /* tuple */[
    26200,
    "um"
  ],
  /* tuple */[
    26206,
    "us"
  ],
  /* tuple */[
    26212,
    "uy"
  ],
  /* tuple */[
    26213,
    "uz"
  ],
  /* tuple */[
    26411,
    "va"
  ],
  /* tuple */[
    26413,
    "vc"
  ],
  /* tuple */[
    26415,
    "ve"
  ],
  /* tuple */[
    26417,
    "vg"
  ],
  /* tuple */[
    26419,
    "vi"
  ],
  /* tuple */[
    26424,
    "vn"
  ],
  /* tuple */[
    26431,
    "vu"
  ],
  /* tuple */[
    26639,
    "wf"
  ],
  /* tuple */[
    26652,
    "ws"
  ],
  /* tuple */[
    27084,
    "ye"
  ],
  /* tuple */[
    27099,
    "yt"
  ],
  /* tuple */[
    27303,
    "za"
  ],
  /* tuple */[
    27315,
    "zm"
  ],
  /* tuple */[
    27325,
    "zw"
  ],
  /* tuple */[
    4849453,
    "as"
  ],
  /* tuple */[
    4997748,
    "do"
  ],
  /* tuple */[
    5246170,
    "in"
  ],
  /* tuple */[
    5793412,
    "to"
  ],
  /* tuple */[
    5840025,
    "uae"
  ],
  /* tuple */[
    8553978,
    "sandwich islands"
  ],
  /* tuple */[
    17180744,
    "taiwan"
  ],
  /* tuple */[
    23499273,
    "spain"
  ],
  /* tuple */[
    25960609,
    "algeria"
  ],
  /* tuple */[
    43329456,
    "micronesia"
  ],
  /* tuple */[
    46974408,
    "comoros"
  ],
  /* tuple */[
    51798339,
    "macau"
  ],
  /* tuple */[
    52250117,
    "malta"
  ],
  /* tuple */[
    60351376,
    "morocco"
  ],
  /* tuple */[
    60562524,
    "jamaica"
  ],
  /* tuple */[
    79094511,
    "sudan"
  ],
  /* tuple */[
    80023190,
    "wallis and futuna"
  ],
  /* tuple */[
    86984768,
    "australia"
  ],
  /* tuple */[
    96077732,
    "suriname"
  ],
  /* tuple */[
    101507004,
    "hong kong"
  ],
  /* tuple */[
    111863777,
    "trinidad"
  ],
  /* tuple */[
    111998492,
    "colombia"
  ],
  /* tuple */[
    124150756,
    "syria"
  ],
  /* tuple */[
    133512000,
    "moldova"
  ],
  /* tuple */[
    154310451,
    "germany"
  ],
  /* tuple */[
    183735918,
    "turkey"
  ],
  /* tuple */[
    187676310,
    "cyprus"
  ],
  /* tuple */[
    188739686,
    "luxembourg"
  ],
  /* tuple */[
    191985735,
    "cook islands"
  ],
  /* tuple */[
    192919179,
    "san marino"
  ],
  /* tuple */[
    198494675,
    "guadeloupe"
  ],
  /* tuple */[
    199524132,
    "afghanistan"
  ],
  /* tuple */[
    201361717,
    "mexico"
  ],
  /* tuple */[
    226199893,
    "austria"
  ],
  /* tuple */[
    226605180,
    "reunion"
  ],
  /* tuple */[
    227598453,
    "tuvalu"
  ],
  /* tuple */[
    246296615,
    "gabon"
  ],
  /* tuple */[
    270234992,
    "timorleste"
  ],
  /* tuple */[
    304247879,
    "ireland"
  ],
  /* tuple */[
    306806134,
    "el salvador"
  ],
  /* tuple */[
    314653779,
    "french territories"
  ],
  /* tuple */[
    315099830,
    "iceland"
  ],
  /* tuple */[
    316580436,
    "somalia"
  ],
  /* tuple */[
    317439219,
    "zimbabwe"
  ],
  /* tuple */[
    321003244,
    "brazil"
  ],
  /* tuple */[
    323873619,
    "ghana"
  ],
  /* tuple */[
    338321549,
    "dominican republic"
  ],
  /* tuple */[
    338545517,
    "tonga"
  ],
  /* tuple */[
    360698541,
    "greece"
  ],
  /* tuple */[
    360943231,
    "svalbard"
  ],
  /* tuple */[
    369496941,
    "guatemala"
  ],
  /* tuple */[
    378187045,
    "nauru"
  ],
  /* tuple */[
    385166436,
    "jordan"
  ],
  /* tuple */[
    389448496,
    "vanuatu"
  ],
  /* tuple */[
    407618475,
    "tokelau"
  ],
  /* tuple */[
    418882393,
    "venezuela"
  ],
  /* tuple */[
    422292868,
    "nepal"
  ],
  /* tuple */[
    427601114,
    "vatican city"
  ],
  /* tuple */[
    430132158,
    "heard island"
  ],
  /* tuple */[
    441915774,
    "french guiana"
  ],
  /* tuple */[
    447432169,
    "andorra"
  ],
  /* tuple */[
    449834901,
    "lebanon"
  ],
  /* tuple */[
    450282424,
    "vietnam"
  ],
  /* tuple */[
    462972573,
    "ecuador"
  ],
  /* tuple */[
    466204473,
    "niger"
  ],
  /* tuple */[
    494662521,
    "liechtenstein"
  ],
  /* tuple */[
    501438108,
    "albania"
  ],
  /* tuple */[
    505746859,
    "belize"
  ],
  /* tuple */[
    517024535,
    "swaziland"
  ],
  /* tuple */[
    529018841,
    "equatorial guinea"
  ],
  /* tuple */[
    542196941,
    "brunei"
  ],
  /* tuple */[
    558717452,
    "honduras"
  ],
  /* tuple */[
    569814358,
    "mozambique"
  ],
  /* tuple */[
    572135621,
    "haiti"
  ],
  /* tuple */[
    576598449,
    "indian ocean territory"
  ],
  /* tuple */[
    597117901,
    "marshall islands"
  ],
  /* tuple */[
    597209438,
    "united states"
  ],
  /* tuple */[
    597301507,
    "bangladesh"
  ],
  /* tuple */[
    602160407,
    "bulgaria"
  ],
  /* tuple */[
    607479808,
    "costa rica"
  ],
  /* tuple */[
    609260765,
    "burundi"
  ],
  /* tuple */[
    612031079,
    "maldives"
  ],
  /* tuple */[
    630306083,
    "aruba"
  ],
  /* tuple */[
    640577703,
    "argentina"
  ],
  /* tuple */[
    653878682,
    "cocos islands"
  ],
  /* tuple */[
    655602046,
    "tanzania"
  ],
  /* tuple */[
    693412713,
    "senegal"
  ],
  /* tuple */[
    693887796,
    "saint lucia"
  ],
  /* tuple */[
    717687094,
    "finland"
  ],
  /* tuple */[
    737819424,
    "cambodia"
  ],
  /* tuple */[
    747008027,
    "france"
  ],
  /* tuple */[
    749768651,
    "pitcairn islands"
  ],
  /* tuple */[
    757023541,
    "puerto rico"
  ],
  /* tuple */[
    765117051,
    "ukraine"
  ],
  /* tuple */[
    792093131,
    "namibia"
  ],
  /* tuple */[
    805087341,
    "montserrat"
  ],
  /* tuple */[
    810223410,
    "christmas island"
  ],
  /* tuple */[
    811284976,
    "benin"
  ],
  /* tuple */[
    812714174,
    "norway"
  ],
  /* tuple */[
    814173678,
    "new guinea"
  ],
  /* tuple */[
    847366848,
    "dominica"
  ],
  /* tuple */[
    859940690,
    "kyrgyzstan"
  ],
  /* tuple */[
    867660795,
    "norfolk island"
  ],
  /* tuple */[
    883471155,
    "martinique"
  ],
  /* tuple */[
    886450138,
    "sri lanka"
  ],
  /* tuple */[
    913418011,
    "malawi"
  ],
  /* tuple */[
    913775645,
    "saudi arabia"
  ],
  /* tuple */[
    916024645,
    "new caledonia"
  ],
  /* tuple */[
    920993610,
    "liberia"
  ],
  /* tuple */[
    940420171,
    "aland islands"
  ],
  /* tuple */[
    942827534,
    "canada"
  ],
  /* tuple */[
    944659998,
    "uruguay"
  ],
  /* tuple */[
    951648485,
    "myanmar"
  ],
  /* tuple */[
    956479095,
    "saint pierre"
  ],
  /* tuple */[
    961964468,
    "bermuda"
  ],
  /* tuple */[
    970840658,
    "american samoa"
  ],
  /* tuple */[
    976981536,
    "scotland"
  ],
  /* tuple */[
    984566718,
    "portugal"
  ],
  /* tuple */[
    988917843,
    "burma"
  ],
  /* tuple */[
    994243651,
    "french polynesia"
  ],
  /* tuple */[
    994958479,
    "tunisia"
  ],
  /* tuple */[
    997446444,
    "madagascar"
  ],
  /* tuple */[
    1015368809,
    "ethiopia"
  ],
  /* tuple */[
    1017288775,
    "seychelles"
  ],
  /* tuple */[
    1022935984,
    "montenegro"
  ],
  /* tuple */[
    1023289176,
    "belarus"
  ],
  /* tuple */[
    1025777415,
    "saint helena"
  ],
  /* tuple */[
    1028715279,
    "palau"
  ],
  /* tuple */[
    1041538679,
    "india"
  ],
  /* tuple */[
    1052606134,
    "eritrea"
  ],
  /* tuple */[
    1052648513,
    "philippines"
  ],
  /* tuple */[
    1054336090,
    "denmark"
  ],
  /* tuple */[
    1055664571,
    "russia"
  ],
  /* tuple */[
    1063006766,
    "greenland"
  ],
  /* tuple */[
    1073399252,
    "uzbekistan"
  ]
];

function countryNameToJs(param) {
  return Js_mapperRt.binarySearch(491, param, jsMapperConstantArray);
}

function countryNameFromJs(param) {
  return Js_mapperRt.revSearch(491, jsMapperConstantArray, param);
}

function make(className, as_, name, children) {
  return ReasonReact.wrapJsForReason(SemanticUiReact.Flag, {
              className: Js_null_undefined.fromOption(className),
              as: Js_null_undefined.fromOption(as_),
              name: countryNameToJs(name)
            }, children);
}

exports.countryNameToJs = countryNameToJs;
exports.countryNameFromJs = countryNameFromJs;
exports.make = make;
/* ReasonReact Not a pure module */
